### ISSUE TITLE
Main project structure

### ISSUE THREAD

**Issue by leomcabral** [VanHack/binners-project-api#6]
I propose the following structure for the root repo directory.

├── android-api-client
├── android-app
├── ios-api-client
├── ios-app
├── rest-api
└── web-app

- **android-api-client** - Java code that will interact with the server api back-end (rest-api).
- **android-app** - Android project with the mobile interface.
- **ios-api-client** - iOS code that will interact with the server api back-end (rest-api).
- **ios-app** - iOS project with the mobile interface.
- **rest-api** - Core back-end functionality. Provides the REST end-points (NodeJS + Hapi + Mongo).
- **web-app** - Project that holds the HTML5 interface (future).

Any suggestions or modifications to this structure?

**Comment by digoreis** [comment]
@leomcabral I think better to wait in multiple repositories, to avoid downloading unnecessary parts.
Repo : android
Repo: iOS
Repo: API
Repo: Web

Each team can follow your workflow.

**Comment by leomcabral** [comment]
@digoreis I completely agree with you. But to the sake of simplicity the team voted to be one repo.

**Comment by matheusruschel** [comment]
We should cast votes again, cause I also agree with you guys, haha. we could make this repo the server repo, then each team can create their own repo

**Comment by felipefcm** [comment]
I think both separated folders and repos are fine, usually the latter is chosen if the projects are very different from each other. I don't know if that's the case.
The advantages of using just one repo is that all the art resources can be shared easily, but of course they can be shared using other services like Dropbox or Drive.

**Comment by samuelcastro** [comment]
Already created the initial foundation, closing this issue.
